apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: webhook-service
  creationTimestamp: null
  labels:
    app-version: v1
  name: aqua-scanner-operator-webhook-service
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app-version: v1
    control-plane: controller-manager
status:
  loadBalancer: {}
