apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app-version: v1
    control-plane: controller-manager
  name: aqua-scanner-operator-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    app-version: v1
    control-plane: controller-manager
status:
  loadBalancer: {}
