# permissions for end users to view aquascanneraccounts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: aquascanneraccount-viewer-role
rules:
- apiGroups:
  - mamoa.devops.gov.bc.ca.devops.gov.bc.ca
  resources:
  - aquascanneraccounts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mamoa.devops.gov.bc.ca.devops.gov.bc.ca
  resources:
  - aquascanneraccounts/status
  verbs:
  - get
