# The following patch enables a conversion webhook for the CRD
[
  {
    "op": "add",
    "path": "/spec/versions/0/deprecated",
    # This indicates the v1alpha1 version of the custom resource is deprecated.
    # API requests to this version receive a warning header in the server response.
    "value": true,
    # This overrides the default warning returned to API clients making v1alpha1 API requests.
  },
  {
    "op": "add",
    "path": "/spec/versions/0/deprecationWarning",
    # This indicates the v1alpha1 version of the custom resource is deprecated.
    # API requests to this version receive a warning header in the server response.
    "value": "mamoa.devops.gov.bc.ca/v1alpha1 AquaScannerAccount is deprecated. Please upgrade to v1alpha2"
  }
]