# The following patch enables a conversion webhook for the CRD
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: aquascanneraccounts.mamoa.devops.gov.bc.ca
spec:
  versions:
  - name: v1alpha1
    # This indicates the v1alpha1 version of the custom resource is deprecated.
    # API requests to this version receive a warning header in the server response.
    deprecated: true
    # This overrides the default warning returned to API clients making v1alpha1 API requests.
    deprecationWarning: "mamoa.devops.gov.bc.ca/v1alpha1 AquaScannerAccount is deprecated. Please upgrade to v1alpha2"
